# SPDX-License-Identifier: GPL-3.0-only

# File based on:
# https://github.com/pybind/cmake_example/blob/master/conda.recipe/meta.yaml

package:
  name: xmipp4-compute-metal
  version: "0.1.0"

about:
  summary: Apple Metal compute library for xmipp4
  license_file: LICENSE

source:
  path: ../

requirements:
  host:
    - python
    - pip
    - scikit-build-core
    - xmipp4-core=0.1

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake>=3.16
    - ninja

build:
  number: 0
