name: Build and Test

on:
  pull_request:
  
  workflow_dispatch:

jobs:
  build_with_cmake:
    name: CMake (macOS)
    strategy:
      matrix:
        os:
        - macos-latest # ARM
        compiler: 
        - {cc: gcc, cxx: g++}
        - {cc: clang, cxx: clang++}
  
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: Release
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install xmipp4-core
        working-directory: ${{ github.workspace }}/../
        run: |
          git clone https://github.com/gigabit-clowns/xmipp4-core.git
          cd xmipp4-core
          git checkout tags/development
          pip install --no-index --find-links=dist xmipp4-core

      - name: Configure and build with CMake
        uses: threeal/cmake-action@v2
        with:
          source-dir: ${{ github.workspace }}
          build-dir: "${{ github.workspace }}/build"
          c-compiler: ${{ matrix.compiler.cc }}
          cxx-compiler: ${{ matrix.compiler.cxx }}
          options: |
            CMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
            CMAKE_OSX_ARCHITECTURES=arm64
          run-build: true
          build-args: --config ${{ env.BUILD_TYPE }}

      - name: Run tests
        working-directory: "${{ github.workspace }}/build"
        run: ctest -C ${{ env.BUILD_TYPE }} -T test --rerun-failed --output-on-failure
